#!/usr/bin/bash
# Copyright (C) 2024 Jakepy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.



path_file=$1

function main {
    if [ -z "$path_file" ]; then
        echo "Error: required directory name."
        echo "Use: $0 <Path file>"
        exit 1
    fi

    class_name=$(basename "$path_file" .java)

    javac "$path_file"

    if [ $? -eq 0 ]; then
        java "$class_name"
    else
        echo "Error: Compilation failed."
        exit 1
    fi
}

main

